version: "2.1"

volumes:
  pihole_config:
  dnsmasq_config:
  unms_config:
  unifi_config:
  unifi_log:
  unifi_log2:
  unifi_run:
  unifi_run2:
  unifi_work:

services:
  pihole:
    build:
      context: ./balena-pihole/pihole
    privileged: true
    container_name: pihole
    restart: unless-stopped
    network_mode: host
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      - TZ=${TIME_ZONE:-America/New_York}
    volumes:
      - "pihole_config:/etc/pihole"
      - "dnsmasq_config:/etc/dnsmasq.d"

  unifi:
    image: ryansch/unifi-rpi:6.2.26-arm64v8
    container_name: unifi
    restart: unless-stopped
    network_mode: host
    ports:
      - "3478:3478/udp"
      - "5514:5514"
      - "8080:8080"
      - "8443:8443"
      - "8843:8843"
      - "6789:6789"
      - "27117:27117"
      - "1900:1900/udp"
      - "10001:10001/udp"
    environment:
      JAVA_OPTS: -Xmx512M
    volumes:
      - "unifi_config:/var/lib/unifi"
      - "unifi_log:/usr/lib/unifi/logs"
      - "unifi_log2:/var/log/unifi"
      - "unifi_run:/usr/lib/unifi/run"
      - "unifi_run2:/run/unifi"
      - "unifi_work:/usr/lib/unifi/work"

  unms:
    image: nico640/docker-unms:1.3.10
    container_name: unms
    restart: unless-stopped
    ports:
      - "4443:443"
      - "4080:80"
      - "2025:2025/udp"
    environment:
      - TZ=${TIME_ZONE:-America/New_York}
      - SECURE_LINK_SECRET=${SEC_LINK_SECRET}
      - PUBLIC_HTTPS_PORT=4443
      - PUBLIC_WS_PORT=4443
    volumes:
      - "unms_config:/config"
