version: '2.1'

volumes:
  pihole_config:
  dnsmasq_config:
  dnscrypt_config:
  unifi-data:
  unms-data:

services:
  pihole:
    build: ./balena-pihole/pihole
    privileged: true
    volumes:
      - 'pihole_config:/etc/pihole'
      - 'dnsmasq_config:/etc/dnsmasq.d'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    network_mode: host

  dnscrypt-proxy:
    build: ./balena-pihole/dnscrypt-proxy
    volumes:
      - 'dnscrypt_config:/config'
    ports:
      - '5053:5053/udp'
  
  unifi:
    build: ./balena-ubnt/unifi
    ports:
      # See https://help.ubnt.com/hc/en-us/articles/218506997-UniFi-Ports-Used
      - "3478:3478/udp"
      - "5514:5514"
      - "8080:8080"
      - "8843:8843"
      - "6789:6789"
      - "27117:27117"
      - "1900:1900/udp"
      - "10001:10001/udp"
    volumes:
      - "unifi-data:/unifi"
  
  unms:
    build: ./balena-ubnt/unms
    ports:
      - "4443:443"
      - "4080:80"
    volumes:
     - "unms-data:/config"
