version: '2.1'

volumes:
  pihole_config:
  dnsmasq_config:
  unifi-data:
  unms-data:

services:
  pihole:
    build: ./balena-pihole/pihole
    privileged: true
    volumes:
      - 'pihole_config:/etc/pihole'
      - 'dnsmasq_config:/etc/dnsmasq.d'
    cap_add:
      - 'NET_ADMIN'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    network_mode: host
    restart: unless-stopped

  dnscrypt-proxy:
    build: ./balena-pihole/dnscrypt-proxy
    ports:
      - '5300:53/tcp'
      - '5300:53/udp'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    restart: unless-stopped
  
  unifi:
    build: ./balena-ubnt/unifi
    ports:
      # See https://help.ubnt.com/hc/en-us/articles/218506997-UniFi-Ports-Used
      - "3478:3478/udp"
      - "6789:6789"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "10001:10001/udp"
    volumes:
      - "unifi-data:/unifi"
    restart: unless-stopped
  
  unms:
    build: ./balena-ubnt/unms
    ports:
      - "4443:443"
      - "4080:80"
    volumes:
     - "unms-data:/config"
    restart: unless-stopped
