version: '2.1'

volumes:
  pihole_config:
  dnsmasq_config:
  unms-data:
  unifi_config:
  unifi_log:
  unifi_log2:
  unifi_run:
  unifi_run2:
  unifi_work:

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    dns:
      - '1.1.1.1'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      - TZ=${TIME_ZONE:-America/New_York}
    volumes:
      - 'pihole_config:/etc/pihole'
      - 'dnsmasq_config:/etc/dnsmasq.d'
    restart: unless-stopped

  unifi:
    image: 'ryansch/unifi-rpi:latest'
    container_name: unifi
    ports:
      - '3478:3478/udp'
      - '5514:5514'
      - '8080:8080'
      - '8443:8443'
      - '8843:8843'
      - '6789:6789'
      - '27117:27117'
      - '1900:1900/udp'
      - '10001:10001/udp'
    volumes:
      - 'unifi_config:/var/lib/unifi'
      - 'unifi_log:/usr/lib/unifi/logs'
      - 'unifi_log2:/var/log/unifi'
      - 'unifi_run:/usr/lib/unifi/run'
      - 'unifi_run2:/run/unifi'
      - 'unifi_work:/usr/lib/unifi/work'
    restart: unless-stopped

  unms:
    image: nico640/docker-unms:latest
    container_name: unms
    ports:
      - "4443:443"
      - "4080:80"
      - "2025:2025/udp"
    environment:
      - TZ=${TIME_ZONE:-America/New_York}
      - SECURE_LINK_SECRET=${SEC_LINK_SECRET}
      - PUBLIC_HTTPS_PORT=4443
      - PUBLIC_WS_PORT=4443
    volumes:
      - unms-data:/config
    restart: unless-stopped
