version: '2.1'

volumes:
  pihole_config:
  unifi-data:
  unms-data:
  config:
  log:
  log2:
  run:
  run2:
  work:

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    network_mode: host
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    volumes:
      - pihole_config:/etc/pihole
    restart: always

  unifi:
    image: ryansch/unifi-rpi:latest
    container_name: unifi
    network_mode: host
    ports:
      # See https://help.ubnt.com/hc/en-us/articles/218506997-UniFi-Ports-Used
      - "3478:3478/udp"
      - "5514:5514"
      - "8080:8080"
      - "8443:8443"
      - "8843:8843"
      - "6789:6789"
      - "1900:1900/udp"
      - "10001:10001/udp"
      - "27117:27117"
    volumes:
      # Unifi v5.0.7 creates all of these directories (some remain empty)
      - config:/var/lib/unifi
      - log:/usr/lib/unifi/logs
      - log2:/var/log/unifi
      - run:/usr/lib/unifi/run
      - run2:/run/unifi
      - work:/usr/lib/unifi/work
    environment:
      JAVA_OPTS: -Xmx512M
    privileged: true
    restart: always

  unms:
    image: nico640/docker-unms:latest
    container_name: unms
    ports:
      - "4443:443"
      - "4080:80"
      - "2025:2025/udp"
    environment:
      - TZ=${TIME_ZONE:-America/New_York}
      - SECURE_LINK_SECRET=${SEC_LINK_SECRET}
      - PUBLIC_HTTPS_PORT=4443
      - PUBLIC_WS_PORT=4443
    volumes:
      - unms-data:/config
    restart: always
